### ISSUE TITLE
ModuleNotFoundError: No module named 'legion_cffi' 

### ISSUE THREAD

**Issue by songkq** [flexflow/FlexFlow#1095]
Hi, could you please give some advice for this issue?
```
python3 -m pip install .

  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: pybind11 in /usr/local/lib/python3.8/dist-packages (from flexflow==23.9.0) (2.11.1)
Requirement already satisfied: torchaudio>=0.13.1 in /usr/local/lib/python3.8/dist-packages (from flexflow==23.9.0) (2.0.2)
Requirement already satisfied: torch>=1.13.1 in /usr/local/lib/python3.8/dist-packages (from flexflow==23.9.0) (2.0.1)
Requirement already satisfied: regex in /usr/local/lib/python3.8/dist-packages (from flexflow==23.9.0) (2023.8.8)
Requirement already satisfied: qualname>=0.1.0 in /usr/local/lib/python3.8/dist-packages (from flexflow==23.9.0) (0.1.0)
Requirement already satisfied: einops in /usr/local/lib/python3.8/dist-packages (from flexflow==23.9.0) (0.6.1)
Requirement already satisfied: onnx in /usr/local/lib/python3.8/dist-packages (from flexflow==23.9.0) (1.14.1)
Requirement already satisfied: sentencepiece in /usr/local/lib/python3.8/dist-packages (from flexflow==23.9.0) (0.1.99)
Requirement already satisfied: cmake-build-extension in /usr/local/lib/python3.8/dist-packages (from flexflow==23.9.0) (0.5.1)
Requirement already satisfied: requests in /usr/local/lib/python3.8/dist-packages (from flexflow==23.9.0) (2.31.0)
Requirement already satisfied: torchvision>=0.14.1 in /usr/local/lib/python3.8/dist-packages (from flexflow==23.9.0) (0.15.2)
Requirement already satisfied: ninja in /usr/local/lib/python3.8/dist-packages (from flexflow==23.9.0) (1.11.1)
Requirement already satisfied: numpy>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from flexflow==23.9.0) (1.23.5)
Requirement already satisfied: transformers>=4.31.0 in /usr/local/lib/python3.8/dist-packages (from flexflow==23.9.0) (4.32.0)
Requirement already satisfied: Pillow in /usr/local/lib/python3.8/dist-packages (from flexflow==23.9.0) (10.0.0)
Requirement already satisfied: cffi>=1.11.0 in /usr/local/lib/python3.8/dist-packages (from flexflow==23.9.0) (1.15.1)
Requirement already satisfied: keras-preprocessing>=1.1.2 in /usr/local/lib/python3.8/dist-packages (from flexflow==23.9.0) (1.1.2)
Requirement already satisfied: pycparser in /usr/local/lib/python3.8/dist-packages (from cffi>=1.11.0->flexflow==23.9.0) (2.21)
Requirement already satisfied: six>=1.9.0 in /usr/lib/python3/dist-packages (from keras-preprocessing>=1.1.2->flexflow==23.9.0) (1.14.0)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.8/dist-packages (from torch>=1.13.1->flexflow==23.9.0) (4.7.1)
Requirement already satisfied: nvidia-cuda-cupti-cu11==11.7.101 in /usr/local/lib/python3.8/dist-packages (from torch>=1.13.1->flexflow==23.9.0) (11.7.101)
Requirement already satisfied: nvidia-cudnn-cu11==8.5.0.96 in /usr/local/lib/python3.8/dist-packages (from torch>=1.13.1->flexflow==23.9.0) (8.5.0.96)
Requirement already satisfied: sympy in /usr/local/lib/python3.8/dist-packages (from torch>=1.13.1->flexflow==23.9.0) (1.12)
Requirement already satisfied: nvidia-cuda-runtime-cu11==11.7.99 in /usr/local/lib/python3.8/dist-packages (from torch>=1.13.1->flexflow==23.9.0) (11.7.99)
Requirement already satisfied: filelock in /usr/local/lib/python3.8/dist-packages (from torch>=1.13.1->flexflow==23.9.0) (3.12.2)
Requirement already satisfied: nvidia-cusparse-cu11==11.7.4.91 in /usr/local/lib/python3.8/dist-packages (from torch>=1.13.1->flexflow==23.9.0) (11.7.4.91)
Requirement already satisfied: nvidia-nccl-cu11==2.14.3 in /usr/local/lib/python3.8/dist-packages (from torch>=1.13.1->flexflow==23.9.0) (2.14.3)
Requirement already satisfied: nvidia-cusolver-cu11==11.4.0.1 in /usr/local/lib/python3.8/dist-packages (from torch>=1.13.1->flexflow==23.9.0) (11.4.0.1)
Requirement already satisfied: nvidia-nvtx-cu11==11.7.91 in /usr/local/lib/python3.8/dist-packages (from torch>=1.13.1->flexflow==23.9.0) (11.7.91)
Requirement already satisfied: nvidia-curand-cu11==10.2.10.91 in /usr/local/lib/python3.8/dist-packages (from torch>=1.13.1->flexflow==23.9.0) (10.2.10.91)
Requirement already satisfied: nvidia-cublas-cu11==11.10.3.66 in /usr/local/lib/python3.8/dist-packages (from torch>=1.13.1->flexflow==23.9.0) (11.10.3.66)
Requirement already satisfied: nvidia-cufft-cu11==10.9.0.58 in /usr/local/lib/python3.8/dist-packages (from torch>=1.13.1->flexflow==23.9.0) (10.9.0.58)
Requirement already satisfied: triton==2.0.0 in /usr/local/lib/python3.8/dist-packages (from torch>=1.13.1->flexflow==23.9.0) (2.0.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.8/dist-packages (from torch>=1.13.1->flexflow==23.9.0) (3.1)
Requirement already satisfied: nvidia-cuda-nvrtc-cu11==11.7.99 in /usr/local/lib/python3.8/dist-packages (from torch>=1.13.1->flexflow==23.9.0) (11.7.99)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.8/dist-packages (from torch>=1.13.1->flexflow==23.9.0) (3.1.2)
Requirement already satisfied: setuptools in /usr/local/lib/python3.8/dist-packages (from nvidia-cublas-cu11==11.10.3.66->torch>=1.13.1->flexflow==23.9.0) (65.6.3)
Requirement already satisfied: wheel in /usr/local/lib/python3.8/dist-packages (from nvidia-cublas-cu11==11.10.3.66->torch>=1.13.1->flexflow==23.9.0) (0.38.4)
Requirement already satisfied: lit in /usr/local/lib/python3.8/dist-packages (from triton==2.0.0->torch>=1.13.1->flexflow==23.9.0) (16.0.6)
Requirement already satisfied: cmake in /usr/local/lib/python3.8/dist-packages (from triton==2.0.0->torch>=1.13.1->flexflow==23.9.0) (3.27.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.8/dist-packages (from transformers>=4.31.0->flexflow==23.9.0) (23.1)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.8/dist-packages (from transformers>=4.31.0->flexflow==23.9.0) (4.66.1)
Requirement already satisfied: huggingface-hub<1.0,>=0.15.1 in /usr/local/lib/python3.8/dist-packages (from transformers>=4.31.0->flexflow==23.9.0) (0.16.4)
Requirement already satisfied: tokenizers!=0.11.3,<0.14,>=0.11.1 in /usr/local/lib/python3.8/dist-packages (from transformers>=4.31.0->flexflow==23.9.0) (0.13.3)
Requirement already satisfied: safetensors>=0.3.1 in /usr/local/lib/python3.8/dist-packages (from transformers>=4.31.0->flexflow==23.9.0) (0.3.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.8/dist-packages (from transformers>=4.31.0->flexflow==23.9.0) (6.0.1)
Requirement already satisfied: setuptools-scm in /usr/local/lib/python3.8/dist-packages (from cmake-build-extension->flexflow==23.9.0) (7.1.0)
Requirement already satisfied: GitPython in /usr/local/lib/python3.8/dist-packages (from cmake-build-extension->flexflow==23.9.0) (3.1.34)
Requirement already satisfied: protobuf>=3.20.2 in /usr/local/lib/python3.8/dist-packages (from onnx->flexflow==23.9.0) (3.20.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.8/dist-packages (from requests->flexflow==23.9.0) (3.2.0)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/lib/python3/dist-packages (from requests->flexflow==23.9.0) (1.25.8)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests->flexflow==23.9.0) (2019.11.28)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3/dist-packages (from requests->flexflow==23.9.0) (2.8)
Requirement already satisfied: fsspec in /usr/local/lib/python3.8/dist-packages (from huggingface-hub<1.0,>=0.15.1->transformers>=4.31.0->flexflow==23.9.0) (2023.6.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.8/dist-packages (from GitPython->cmake-build-extension->flexflow==23.9.0) (4.0.10)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.8/dist-packages (from jinja2->torch>=1.13.1->flexflow==23.9.0) (2.1.3)
Requirement already satisfied: tomli>=1.0.0 in /usr/local/lib/python3.8/dist-packages (from setuptools-scm->cmake-build-extension->flexflow==23.9.0) (2.0.1)
Requirement already satisfied: mpmath>=0.19 in /usr/local/lib/python3.8/dist-packages (from sympy->torch>=1.13.1->flexflow==23.9.0) (1.3.0)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.8/dist-packages (from gitdb<5,>=4.0.1->GitPython->cmake-build-extension->flexflow==23.9.0) (5.0.0)
Building wheels for collected packages: flexflow
  Building wheel for flexflow (pyproject.toml) ... done
  Created wheel for flexflow: filename=flexflow-23.9.0-cp38-cp38-linux_x86_64.whl size=48670053 sha256=cf1e25cbe883241aad7d8b46d13f08ac7b1abbb9dc00c006f3dc0f30b5190cd5
  Stored in directory: /tmp/pip-ephem-wheel-cache-62ex8s_h/wheels/1e/66/e8/f1d23cae48e6d97723e17f6a8a74100a6897f1791c5711bef4
Successfully built flexflow
Installing collected packages: flexflow
  Attempting uninstall: flexflow
    Found existing installation: flexflow 23.9.0
    Uninstalling flexflow-23.9.0:
      Successfully uninstalled flexflow-23.9.0
Successfully installed flexflow-23.9.0




Traceback (most recent call last):
  File "flexflow_test.py", line 3, in <module>
    ff.init(
  File "/usr/local/lib/python3.8/dist-packages/flexflow/serve/__init__.py", line 216, in init
    from .serve import LLM, SSM, GenerationConfig, GenerationResult
  File "/usr/local/lib/python3.8/dist-packages/flexflow/serve/serve.py", line 15, in <module>
    from flexflow.serve.models import (
  File "/usr/local/lib/python3.8/dist-packages/flexflow/serve/models/__init__.py", line 15, in <module>
    from .llama import FlexFlowLLAMA
  File "/usr/local/lib/python3.8/dist-packages/flexflow/serve/models/llama.py", line 15, in <module>
    from flexflow.core import *
  File "/usr/local/lib/python3.8/dist-packages/flexflow/core/__init__.py", line 30, in <module>
    from legion_cffi import ffi, is_legion_python
ModuleNotFoundError: No module named 'legion_cffi'
```

**Comment by goliaro** [comment]
@songkq Thanks for trying FlexFlow, let me look into this! One thing that could help is if you could try installing again with `python3 -m pip install . --verbose` and send us the full log. In the meantime, if you'd like to try FlexFlow, you can run one of our pre-built Docker images (instructions [here](https://flexflow.readthedocs.io/en/latest/docker.html) )

**Comment by songkq** [comment]
@goliaro Hi, 

I can build docker image from scratch by `FF_GPU_BACKEND=cuda cuda_version=cuda_12.0 ./docker/build.sh flexflow`, but the docker container will crash and exit immediately after executing docker-run on my machine. The pre-built Docker image seems to be the same issue on my machine.

<img width="986" alt="image" src="https://github.com/flexflow/FlexFlow/assets/30183023/c387b700-613f-4077-a09c-9d5a1398c046">

**Comment by goliaro** [comment]
@songkq  For the docker image, could you try running the following command, and send me the output:
```
docker run --gpus all -it --rm --shm-size=8g ghcr.io/flexflow/flexflow-cuda-12.0:latest
```

Do you have the nvidia container runtime installed on your machine? And what OS/linux flavor/version is your machine running?
