### ISSUE TITLE
New to FlexFlow

### ISSUE THREAD

**Issue by Rashad-CSU** [flexflow/FlexFlow#1188]
To whom it may concern, 

Getting an issue (shown at the end) when I try to run the following code in a conda environment. Any guideline would be much appreciated. 

CODE:
import flexflow.serve as ff

ff.init(
        num_gpus=4,
        memory_per_gpu=14000,
        zero_copy_memory_per_node=30000,
        tensor_parallelism_degree=4,
        pipeline_parallelism_degree=1
    )

ISSUE:    
(myenv) kabir@ENS13494:~/PycharmProjects/test_AI_worokload$ python3 test.py > test_log
Traceback (most recent call last):
  File "/home/kabir/PycharmProjects/test_AI_worokload/test.py", line 1, in <module>
    import flexflow.serve as ff
  File "/home/kabir/anaconda3/envs/myenv/lib/python3.9/site-packages/flexflow/serve/__init__.py", line 17, in <module>
    from flexflow.core import *
  File "/home/kabir/anaconda3/envs/myenv/lib/python3.9/site-packages/flexflow/core/__init__.py", line 34, in <module>
    from .flexflow_cffi import *
  File "/home/kabir/anaconda3/envs/myenv/lib/python3.9/site-packages/flexflow/core/flexflow_cffi.py", line 38, in <module>
    from .flexflowlib import ffi, flexflow_library
  File "/home/kabir/anaconda3/envs/myenv/lib/python3.9/site-packages/flexflow/core/flexflowlib.py", line 18, in <module>
    from .flexflow_cffi_header import flexflow_header
ModuleNotFoundError: No module named 'flexflow.core.flexflow_cffi_header'

Warm regards, 
Rashad

**Comment by eddy16112** [comment]
This error usually means flexflow is not built correctly, since the flexflow_cffi_header.py should be created during compilation.

**Comment by lambda7xx** [comment]
it seems you don't install flexflow successfully.

**Comment by Rashad-CSU** [comment]
For the same code, getting the following issue after build. 

(flexflow) kabir@ENS13494:~/PycharmProjects/test_AI_worokload$ python3 test.py > test_log
python3: /home/kabir/PycharmProjects/test_AI_worokload/FlexFlow/deps/legion/runtime/realm/cuda/cuda_module.cc:4444: virtual void Realm::Cuda::CudaModule::initialize(Realm::RuntimeImpl*): Assertion `false' failed.
Aborted (core dumped)

**Comment by eddy16112** [comment]
There should be another error before this assertion, `log_gpu.fatal() << cfg_num_gpus << " GPUs requested, but only " << gpu_count << " available!";`, which tells you are requesting N gpus, but system does not have N gpus available.

**Comment by Rashad-CSU** [comment]
**Thank you for the guidance. Currently, for the following code,** 

import flexflow.serve as ff

ff.init(
        num_gpus=1,
        memory_per_gpu=8000,
        zero_copy_memory_per_node=10000,
        tensor_parallelism_degree=1,
        pipeline_parallelism_degree=1
    )

# Specify the LLM
llm = ff.LLM("decapoda-research/llama-7b-hf")

# Specify a list of SSMs (just one in this case)
ssms=[]
ssm = ff.SSM("JackFram/llama-68m")
ssms.append(ssm)

# Create the sampling configs
generation_config = ff.GenerationConfig(
    do_sample=False, temperature=0.9, topp=0.8, topk=1
)

# Compile the SSMs for inference and load the weights into memory
for ssm in ssms:
    ssm.compile(generation_config)

# Compile the LLM for inference and load the weights into memory
llm.compile(generation_config, ssms=ssms)

result = llm.generate("Here are some travel tips for Tokyo:\n")

**I get the following error.** 

(flexflow) kabir@ENS13494:~/PycharmProjects/test_AI_worokload$ python3 test.py > test_log
Downloading (…)lve/main/config.json: 100%|████████████████████████████████████████████████████████████████████| 427/427 [00:00<00:00, 2.40MB/s]
Downloading (…)lve/main/config.json: 100%|████████████████████████████████████████████████████████████████████| 545/545 [00:00<00:00, 3.32MB/s]
Traceback (most recent call last):
  File "/home/kabir/PycharmProjects/test_AI_worokload/test.py", line 33, in <module>
    ssm.compile(generation_config)
  File "/home/kabir/anaconda3/envs/flexflow/lib/python3.11/site-packages/flexflow/serve/serve.py", line 493, in compile
    super().compile(
  File "/home/kabir/anaconda3/envs/flexflow/lib/python3.11/site-packages/flexflow/serve/serve.py", line 368, in compile
    self.rm.set_max_requests_per_batch(max_requests_per_batch)
  File "/home/kabir/anaconda3/envs/flexflow/lib/python3.11/site-packages/flexflow/core/flexflow_cffi.py", line 4191, in set_max_requests_per_batch
    return ffc().flexflow_request_manager_set_max_requests_per_batch(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kabir/anaconda3/envs/flexflow/lib/python3.11/site-packages/cffi/api.py", line 912, in __getattr__
    make_accessor(name)
  File "/home/kabir/anaconda3/envs/flexflow/lib/python3.11/site-packages/cffi/api.py", line 908, in make_accessor
    accessors[name](name)
  File "/home/kabir/anaconda3/envs/flexflow/lib/python3.11/site-packages/cffi/api.py", line 838, in accessor_function
    value = backendlib.load_function(BType, name)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: function/symbol 'flexflow_request_manager_set_max_requests_per_batch' not found in library '/home/kabir/anaconda3/envs/flexflow/lib/python3.11/site-packages/flexflow/lib/libflexflow.so': /home/kabir/anaconda3/envs/flexflow/lib/python3.11/site-packages/flexflow/lib/libflexflow.so: undefined symbol: flexflow_request_manager_set_max_requests_per_batch
