### ISSUE TITLE
Legion error during integrating Gradio

### ISSUE THREAD

**Issue by april-yyt** [flexflow/FlexFlow#1203]
When integrating Flexflow with Gradio to create chatbots, specifically when initializing the model and then trying to call it within the "predict" function, ran into this segmentation fault error:

`
[0]7251
Num of models: 2
[0 - 151df829b700]  213.838992 {3}{RequestManager}: [1000000]New request tokens: 0 7251
[0 - 151df829b700]  213.839080 {5}{runtime}: [error 606] LEGION ERROR: Creating Legion Future objects from a buffer is only permitted to be performed inside of Legion tasks. (from file /home/ubuntu/FlexFlow/deps/legion/runtime/legion/legion.cc:2500)
For more information see:
http://legion.stanford.edu/messages/error_code.html#error_code_606

Aborted (core dumped)
`

running a backtrace gives the output:
![image](https://github.com/flexflow/FlexFlow/assets/114364211/6cd7dae2-a2dd-47db-81b2-6f36b8d42ff0)

To reproduce the error:
1. Run ff_gradio_2.py or ff_gradio_incr_decoding.py from pull request #1200 
2. After starting the gradio app and the model initialization finishes, send any random message in the app interface, the error would occur.

**Comment by jiazhihao** [comment]
A complete trace is as follows.
```
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7c54859 in __GI_abort () at abort.c:79
#2  0x00007fff6b6bb81b in Legion::Internal::Runtime::report_error_message (id=123, file_name=0x7fff6c50ea40 "/home/ubuntu/FlexFlow/deps/legion/runtime/legion/runtime.cc", 
    line=18882, message=0x7ff38482bba0 "Illegal dummy context execute task!") at /home/ubuntu/FlexFlow/deps/legion/runtime/legion/runtime.cc:31799
#3  0x00007fff6b68c1fa in Legion::Internal::Runtime::execute_task (this=0x55555e2ecb20, ctx=0x0, launcher=..., outputs=0x0)
    at /home/ubuntu/FlexFlow/deps/legion/runtime/legion/runtime.cc:18882
#4  0x00007fff6b1b6335 in Legion::Runtime::execute_task (this=0x55555e2641d0, ctx=0x0, launcher=..., outputs=0x0)
    at /home/ubuntu/FlexFlow/deps/legion/runtime/legion/legion.cc:6308
#5  0x00007ff386898b94 in FlexFlow::RequestManager::prepare_next_batch (this=0x55555e50dca0, old_bc=..., result=...)
    at /home/ubuntu/FlexFlow/src/runtime/request_manager.cc:323
#6  0x00007ff3868a215d in FlexFlow::RequestManager::generate_incr_decoding (this=0x55555e50dca0, llm=0x55555e52cd40, prompts=..., max_seq_length=128)
    at /home/ubuntu/FlexFlow/src/runtime/request_manager.cc:1863
#7  0x00007ff3868a1e09 in FlexFlow::FFModel::generate (this=0x55555e52cd40, prompts=..., max_seq_length=128) at /home/ubuntu/FlexFlow/src/runtime/request_manager.cc:1813
#8  0x00007ff38642c709 in flexflow_model_generate (handle_=..., input_text=0x7ff274004dd0 "Tell me about Tokyo", max_num_chars=36000, output_text=0x7ff274026740 "", 
    max_seq_length=128, output_length_and_tokens=0x7ff2740028a0) at /home/ubuntu/FlexFlow/src/c/flexflow_c.cc:1594
#9  0x00007ffff7702a4a in ffi_call_unix64 () from /opt/conda/lib/python3.10/lib-dynload/../../libffi.so.8
#10 0x00007ffff7701fea in ffi_call_int () from /opt/conda/lib/python3.10/lib-dynload/../../libffi.so.8
#11 0x00007fff7d9f04a4 in cdata_call () from /opt/conda/lib/python3.10/site-packages/_cffi_backend.cpython-310-x86_64-linux-gnu.so
#12 0x000055555568d42b in _PyObject_MakeTpCall (tstate=0x7ff270023280, callable=0x7fff6d16f660, args=<optimized out>, nargs=<optimized out>, keywords=0x0)
    at /usr/local/src/conda/python-3.10.9/Objects/call.c:224
#13 0x0000555555689386 in _PyObject_VectorcallTstate (kwnames=<error reading variable: dwarf2_find_location_expression: Corrupted DWARF expression.>, nargsf=<optimized out>, 
--Type <RET> for more, q to quit, c to continue without paging--
    args=<optimized out>, callable=0x7fff6d16f660, tstate=<error reading variable: dwarf2_find_location_expression: Corrupted DWARF expression.>)
    at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:112
#14 _PyObject_VectorcallTstate (kwnames=0x0, nargsf=<optimized out>, args=0x7ff274004098, callable=0x7fff6d16f660, tstate=<optimized out>)
    at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:99
#15 PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=0x7ff274004098, callable=0x7fff6d16f660)
    at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
#16 call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, trace_info=0x7ff38482d3c0, tstate=<optimized out>)
    at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
#17 _PyEval_EvalFrameDefault (tstate=<optimized out>, f=0x7ff274003ed0, throwflag=<optimized out>) at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4181
#18 0x0000555555693f8f in _PyEval_EvalFrame (throwflag=<error reading variable: dwarf2_find_location_expression: Corrupted DWARF expression.>, 
    f=<error reading variable: dwarf2_find_location_expression: Corrupted DWARF expression.>, 
    tstate=<error reading variable: dwarf2_find_location_expression: Corrupted DWARF expression.>) at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5052
#19 _PyEval_Vector (kwnames=<optimized out>, kwnames@entry=<error reading variable: dwarf2_find_location_expression: Corrupted DWARF expression.>, argcount=<optimized out>, 
    args=<optimized out>, args@entry=<error reading variable: dwarf2_find_location_expression: Corrupted DWARF expression.>, locals=0x0, 
    locals@entry=<error reading variable: dwarf2_find_location_expression: Corrupted DWARF expression.>, con=0x7fff6d49b2f0, 
    con@entry=<error reading variable: dwarf2_find_location_expression: Corrupted DWARF expression.>, tstate=0x7ff270023280, 
    tstate@entry=<error reading variable: dwarf2_find_location_expression: Corrupted DWARF expression.>) at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
#20 _PyFunction_Vectorcall (func=0x7fff6d49b2e0, stack=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>)
    at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
#21 0x0000555555684525 in _PyObject_VectorcallTstate (kwnames=0x0, nargsf=<optimized out>, args=0x7fff6d50a9b0, callable=0x7fff6d49b2e0, tstate=0x7ff270023280)
    at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
--Type <RET> for more, q to quit, c to continue without paging--
#22 PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=0x7fff6d50a9b0, callable=0x7fff6d49b2e0)
    at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
#23 call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, trace_info=0x7ff38482d590, tstate=<optimized out>)
    at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
#24 _PyEval_EvalFrameDefault (tstate=<optimized out>, f=0x7fff6d50a820, throwflag=<optimized out>) at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4198
#25 0x0000555555693f8f in _PyEval_EvalFrame (throwflag=<error reading variable: dwarf2_find_location_expression: Corrupted DWARF expression.>, 
    f=<error reading variable: dwarf2_find_location_expression: Corrupted DWARF expression.>, 
    tstate=<error reading variable: dwarf2_find_location_expression: Corrupted DWARF expression.>) at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5052
#26 _PyEval_Vector (kwnames=<optimized out>, kwnames@entry=<error reading variable: dwarf2_find_location_expression: Corrupted DWARF expression.>, argcount=<optimized out>, 
    args=<optimized out>, args@entry=<error reading variable: dwarf2_find_location_expression: Corrupted DWARF expression.>, locals=0x0, 
    locals@entry=<error reading variable: dwarf2_find_location_expression: Corrupted DWARF expression.>, con=0x7ffeca1fa690, 
    con@entry=<error reading variable: dwarf2_find_location_expression: Corrupted DWARF expression.>, tstate=0x7ff270023280, 
    tstate@entry=<error reading variable: dwarf2_find_location_expression: Corrupted DWARF expression.>) at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
#27 _PyFunction_Vectorcall (func=0x7ffeca1fa680, stack=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>)
    at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
#28 0x0000555555684525 in _PyObject_VectorcallTstate (kwnames=0x0, nargsf=<optimized out>, args=0x7ff27003bff0, callable=0x7ffeca1fa680, tstate=0x7ff270023280)
    at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
#29 PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=0x7ff27003bff0, callable=0x7ffeca1fa680)
    at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
#30 call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, trace_info=0x7ff38482d760, tstate=<optimized out>)
    at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
--Type <RET> for more, q to quit, c to continue without paging--
#31 _PyEval_EvalFrameDefault (tstate=<optimized out>, f=0x7ff27003be70, throwflag=<optimized out>) at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4198
#32 0x0000555555693f8f in _PyEval_EvalFrame (throwflag=<error reading variable: dwarf2_find_location_expression: Corrupted DWARF expression.>, 
    f=<error reading variable: dwarf2_find_location_expression: Corrupted DWARF expression.>, 
    tstate=<error reading variable: dwarf2_find_location_expression: Corrupted DWARF expression.>) at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5052
#33 _PyEval_Vector (kwnames=<optimized out>, kwnames@entry=<error reading variable: dwarf2_find_location_expression: Corrupted DWARF expression.>, argcount=<optimized out>, 
    args=<optimized out>, args@entry=<error reading variable: dwarf2_find_location_expression: Corrupted DWARF expression.>, locals=0x0, 
    locals@entry=<error reading variable: dwarf2_find_location_expression: Corrupted DWARF expression.>, con=0x7ffeca292b10, 
    con@entry=<error reading variable: dwarf2_find_location_expression: Corrupted DWARF expression.>, tstate=0x7ff270023280, 
    tstate@entry=<error reading variable: dwarf2_find_location_expression: Corrupted DWARF expression.>) at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
#34 _PyFunction_Vectorcall (func=0x7ffeca292b00, stack=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>)
    at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
#35 0x00005555557b81b1 in _PyObject_VectorcallTstate (tstate=0x7ff270023280, callable=0x7ffeca292b00, args=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>)
    at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
#36 0x000055555564fc95 in context_run (self=0x7fff6d7ac740, args=0x7fff6d1ad098, nargs=3, kwnames=0x0) at /usr/local/src/conda/python-3.10.9/Python/context.c:665
#37 0x000055555568bd83 in cfunction_vectorcall_FASTCALL_KEYWORDS (func=0x7fff6d4efd80, args=0x7fff6d1ad098, nargsf=<optimized out>, kwnames=0x0)
    at /usr/local/src/conda/python-3.10.9/Objects/methodobject.c:446
#38 0x0000555555689b7c in do_call_core (kwdict=0x0, callargs=0x7fff6d1ad080, func=0x7fff6d4efd80, trace_info=0x7ff38482d9c0, tstate=<optimized out>)
    at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5915
#39 _PyEval_EvalFrameDefault (tstate=<optimized out>, f=0x7ff274000ba0, throwflag=<optimized out>) at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4277
#40 0x0000555555693f8f in _PyEval_EvalFrame (throwflag=<error reading variable: dwarf2_find_location_expression: Corrupted DWARF expression.>, 
    f=<error reading variable: dwarf2_find_location_expression: Corrupted DWARF expression.>, 
--Type <RET> for more, q to quit, c to continue without paging--
    tstate=<error reading variable: dwarf2_find_location_expression: Corrupted DWARF expression.>) at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5052
#41 _PyEval_Vector (kwnames=<optimized out>, kwnames@entry=<error reading variable: dwarf2_find_location_expression: Corrupted DWARF expression.>, argcount=<optimized out>, 
    args=<optimized out>, args@entry=<error reading variable: dwarf2_find_location_expression: Corrupted DWARF expression.>, locals=0x0, 
    locals@entry=<error reading variable: dwarf2_find_location_expression: Corrupted DWARF expression.>, con=0x7fff6d17bc80, 
    con@entry=<error reading variable: dwarf2_find_location_expression: Corrupted DWARF expression.>, tstate=0x7ff270023280, 
    tstate@entry=<error reading variable: dwarf2_find_location_expression: Corrupted DWARF expression.>) at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
#42 _PyFunction_Vectorcall (func=0x7fff6d17bc70, stack=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>)
    at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
#43 0x0000555555684525 in _PyObject_VectorcallTstate (kwnames=0x0, nargsf=<optimized out>, args=0x7fff6d191ae0, callable=0x7fff6d17bc70, tstate=0x7ff270023280)
    at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
#44 PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=0x7fff6d191ae0, callable=0x7fff6d17bc70)
    at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
#45 call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, trace_info=0x7ff38482db90, tstate=<optimized out>)
    at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
#46 _PyEval_EvalFrameDefault (tstate=<optimized out>, f=0x7fff6d191970, throwflag=<optimized out>) at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4198
#47 0x0000555555693f8f in _PyEval_EvalFrame (throwflag=<error reading variable: dwarf2_find_location_expression: Corrupted DWARF expression.>, 
    f=<error reading variable: dwarf2_find_location_expression: Corrupted DWARF expression.>, 
    tstate=<error reading variable: dwarf2_find_location_expression: Corrupted DWARF expression.>) at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5052
#48 _PyEval_Vector (kwnames=<optimized out>, kwnames@entry=<error reading variable: dwarf2_find_location_expression: Corrupted DWARF expression.>, argcount=<optimized out>, 
    args=<optimized out>, args@entry=<error reading variable: dwarf2_find_location_expression: Corrupted DWARF expression.>, locals=0x0, 
    locals@entry=<error reading variable: dwarf2_find_location_expression: Corrupted DWARF expression.>, con=0x7fff7e931fd0, 
--Type <RET> for more, q to quit, c to continue without paging--
    con@entry=<error reading variable: dwarf2_find_location_expression: Corrupted DWARF expression.>, tstate=0x7ff270023280, 
    tstate@entry=<error reading variable: dwarf2_find_location_expression: Corrupted DWARF expression.>) at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
#49 _PyFunction_Vectorcall (func=0x7fff7e931fc0, stack=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>)
    at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
#50 0x0000555555684525 in _PyObject_VectorcallTstate (kwnames=0x0, nargsf=<optimized out>, args=0x7fff6d1b5e60, callable=0x7fff7e931fc0, tstate=0x7ff270023280)
    at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
#51 PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=0x7fff6d1b5e60, callable=0x7fff7e931fc0)
    at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
#52 call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, trace_info=0x7ff38482dd60, tstate=<optimized out>)
    at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
#53 _PyEval_EvalFrameDefault (tstate=<optimized out>, f=0x7fff6d1b5cf0, throwflag=<optimized out>) at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4198
#54 0x000055555569f8cd in _PyEval_EvalFrame (throwflag=<error reading variable: dwarf2_find_location_expression: Corrupted DWARF expression.>, 
    f=<error reading variable: dwarf2_find_location_expression: Corrupted DWARF expression.>, 
    tstate=<error reading variable: dwarf2_find_location_expression: Corrupted DWARF expression.>) at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5052
#55 _PyEval_Vector (kwnames=0x0, kwnames@entry=<error reading variable: dwarf2_find_location_expression: Corrupted DWARF expression.>, argcount=1, 
    argcount@entry=<error reading variable: dwarf2_find_location_expression: Corrupted DWARF expression.>, args=0x7ff38482de48, 
    args@entry=<error reading variable: dwarf2_find_location_expression: Corrupted DWARF expression.>, locals=0x0, 
    locals@entry=<error reading variable: dwarf2_find_location_expression: Corrupted DWARF expression.>, con=0x7fff7e931d90, 
    con@entry=<error reading variable: dwarf2_find_location_expression: Corrupted DWARF expression.>, tstate=0x7ff270023280, 
    tstate@entry=<error reading variable: dwarf2_find_location_expression: Corrupted DWARF expression.>) at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
#56 _PyFunction_Vectorcall (kwnames=0x0, nargsf=1, stack=0x7ff38482de48, func=0x7fff7e931d80) at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
--Type <RET> for more, q to quit, c to continue without paging--
#57 _PyObject_VectorcallTstate (kwnames=0x0, nargsf=1, args=0x7ff38482de48, callable=0x7fff7e931d80, tstate=0x7ff270023280)
    at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
#58 method_vectorcall (method=<optimized out>, args=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>)
    at /usr/local/src/conda/python-3.10.9/Objects/classobject.c:61
#59 0x00005555557801e5 in thread_run (boot_raw=0x7fff6d4d3270) at /usr/local/src/conda/python-3.10.9/Modules/_threadmodule.c:1090
#60 0x0000555555780194 in pythread_wrapper (arg=<optimized out>) at /usr/local/src/conda/python-3.10.9/Python/thread_pthread.h:248
#61 0x00007ffff7f92609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#62 0x00007ffff7d51133 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```
