### ISSUE TITLE
FFModel.compile crashes when metrics=None

### ISSUE THREAD

**Issue by suranap** [flexflow/FlexFlow#1218]
https://github.com/flexflow/FlexFlow/blob/1105f4e157afc67ccce7df0e9aef601d7490e61b/python/flexflow/core/flexflow_cffi.py#L3521

This fails when `metrics is None`, as allowed by the function signature: 

`def compile(self, optimizer=None, loss_type=None, metrics=None, comp_mode=None):`

```
Traceback (most recent call last):
  File "build/deps/legion/bindings/python/legion_top.py", line 475, in legion_python_ma\
in
    run_path(args[start], '__main__')
  File "build/deps/legion/bindings/python/legion_top.py", line 295, in run_path
    exec(code, module.__dict__, module.__dict__)
  File "./examples/python/pytorch/mt5/mt5_ff.py", line 218, in <module>
    top_level_task()
  File "./examples/python/pytorch/mt5/mt5_ff.py", line 153, in top_level_task
    metrics=None
  File "python/flexflow/core/flexflow_cffi.py", line 2051, in compile
    for metric in metrics:
TypeError: 'NoneType' object is not iterable
```

**Comment by jiazhihao** [comment]
Instead of setting it to `None`, can you try to pass an empty list?
