### ISSUE TITLE
compute_metrics() not implemented in the Pybind11 backend.

### ISSUE THREAD

**Issue by jiazhihao** [flexflow/FlexFlow#198]
compute_metrics() is currently not implemented in the Pybind11 backend, causing attribute errors when calling `model.evaluate` w/ Pybind11. The issue can be deterministically reproduced by the following command line:
```
$FF_HOME/examples/python/keras/seq_mnist_mlp.py -ll:py 1 -ll:gpu 1 -ll:fsize 3048 -ll:zsize 12192 -b 64
```
and the error message is as follows
```
Traceback (most recent call last):
  File "/home/ubuntu/FlexFlow/python/flexflow/core/flexflow_top.py", line 196, in flexflow_top_level_task
    run_path(args[start], run_name='__main__')
  File "/home/ubuntu/FlexFlow/python/flexflow/core/flexflow_top.py", line 146, in run_path
    exec(code, module.__dict__, module.__dict__)
  File "/home/ubuntu/FlexFlow/examples/python/keras/seq_mnist_mlp.py", line 60, in <module>
    top_level_task()
  File "/home/ubuntu/FlexFlow/examples/python/keras/seq_mnist_mlp.py", line 56, in top_level_task
    model.evaluate(x=x_train, y=y_train)
  File "/home/ubuntu/FlexFlow/python/flexflow/keras/models/base_model.py", line 282, in evaluate
    self._train(1, callbacks, eval=True)
  File "/home/ubuntu/FlexFlow/python/flexflow/keras/models/base_model.py", line 389, in _train
    self._ffmodel.compute_metrics()
AttributeError: 'flexflow.core.flexflow_bindings.FFModel' object has no attribute 'compute_metrics'
flexflow_python: /home/ubuntu/FlexFlow/deps/legion/runtime/realm/python/python_module.cc:978: virtual void Realm::LocalPythonProcessor::execute_task(Realm::Processor::TaskFuncID, const Realm::ByteArrayRef&): Assertion `0' failed.
```

**Comment by eddy16112** [comment]
fixed in https://github.com/flexflow/FlexFlow/pull/199
