### ISSUE TITLE
Python import error

### ISSUE THREAD

**Issue by jiazhihao** [flexflow/FlexFlow#22]
I am getting the following error when testing the Python interface:
```
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/zhihao/FlexFlow/python/flexflow/core/flexflow_top.py", line 195, in flexflow_top_level_task
    run_path(args[start], run_name='__main__')
  File "/autofs/nccs-svm1_home1/zhihao/FlexFlow/python/flexflow/core/flexflow_top.py", line 145, in run_path
    exec(code, module.__dict__, module.__dict__)
  File "example/mlp.py", line 3, in <module>
    from flexflow.keras.datasets import mnist
  File "/autofs/nccs-svm1_home1/zhihao/FlexFlow/python/flexflow/keras/__init__.py", line 2, in <module>
    from . import datasets
  File "/autofs/nccs-svm1_home1/zhihao/FlexFlow/python/flexflow/keras/datasets/__init__.py", line 5, in <module>
    from . import reuters
  File "/autofs/nccs-svm1_home1/zhihao/FlexFlow/python/flexflow/keras/datasets/reuters.py", line 9, in <module>
    from ..preprocessing.sequence import _remove_long_seq
  File "/autofs/nccs-svm1_home1/zhihao/FlexFlow/python/flexflow/keras/preprocessing/__init__.py", line 7, in <module>
    import keras_preprocessing
```

Is keras_preprocessing our package or an external package?

**Comment by eddy16112** [comment]
Sorry I forgot to add it to the requirement.txt. It is an external package.

**Comment by eddy16112** [comment]
By the way, the test.sh in the python folder contains all tests, you can try it. The last two tests sometimes may fail, but the problem comes from the models, not flexflow.

**Comment by jiazhihao** [comment]
Installing keras_preprocessing fixes the problem.
