### ISSUE TITLE
Incompatible Python version raised by python (flexflow/driver)

### ISSUE THREAD

**Issue by LandonWong** [flexflow/FlexFlow#283]
Hello,

FlexFlow did the compilation flawlessly. But when I tried to test it, I encountered the following problem:

```
$ ./flexflow_python example/alexnet.py -ll:py 1 -ll:gpu 1 -ll:zsize 30000 -ll:fsize 10000

[0 - 2b56d73effc0]    0.165826 {3}{Mapper}: No strategy file provided. Use default data parallelism.
[0 - 2b56d73effc0]    0.166055 {3}{Mapper}: No strategy file provided. Use default data parallelism.
[0 - 2b56d73effc0]    0.166118 {3}{Mapper}: No strategy file provided. Use default data parallelism.
[0 - 2b56d75f3fc0]    0.381198 {6}{python}: unable to import Python module flexflow.core
Traceback (most recent call last):
  File "/work/03924/xuehaiq/maverick2/wsy_workspace/flexflow/FlexFlow/python/flexflow/__init__.py", line 17, in <module>
    from .driver import flexflow_driver
  File "/work/03924/xuehaiq/maverick2/wsy_workspace/flexflow/FlexFlow/python/flexflow/driver.py", line 25, in <module>
    raise Exception('Incompatible Python version')
Exception: Incompatible Python version
flexflow_python: /work/03924/xuehaiq/maverick2/wsy_workspace/flexflow/FlexFlow/deps/legion/runtime/realm/python/python_module.cc:229: Realm::PyObject* Realm::PythonInterpreter::find_or_import_function(const Realm::PythonSourceImplementation*): Assertion `0' failed.
Aborted (core dumped)
```

I think it is python paths related issue, because there are both python2.7 and 3.8 there. I have read the code, when version < 3.6 it will raise this error. So I tried to specify the path manually as follows:

+ First attempt: modified `python/Makefile`, manually specified the `PYTHON_EXE`, `PYTHON_ROOT` and `PYTHON_LIB`, but it still didn't work.
+ Second attempt: Set `PYTHON_EXE`, `PYTHON_ROOT` and `PYTHON_LIB` as environment variables in the shell, didn't work either

Thanks for your help!

**Comment by LandonWong** [comment]
I think it is similar to #29 , but this auto detecting didn't work for me

**Comment by eddy16112** [comment]
First, you can check the python version. Just run
```
./flexflow_python -ll:py 1
```
You will be in the interactive mode, then run the following code:
```
import sys
print(sys.version)
```
Make sure the version is 3.8

Second, there is another error:
```
[0 - 2b56d75f3fc0]    0.381198 {6}{python}: unable to import Python module flexflow.core
```
You will need to `export PYTHONPATH=/path-flexflow-root/python:$PYTHONPATH`

**Comment by LandonWong** [comment]
Thanks. I wonder how to manually specify the python path, because even after I straightly modified `deps/pybind11/tools/FindPythonLibsNew.cmake` and force to specify the path to 3.8, it doesn't work either, always 2.7 (in gcc lib).  @eddy16112

**Comment by LandonWong** [comment]
It works. Many thanks!
