### ISSUE TITLE
Python type error in flexflow_cbinding.py

### ISSUE THREAD

**Issue by jiazhihao** [flexflow/FlexFlow#29]
I encountered the following type error when training AlexNet with the most recent Python implementation. The command line to reproduce the failure is `./flexflow_python example/alexnet.py -ll:py 1 -ll:gpu 1 -ll:zsize 30000 -ll:fsize 10000`
```
[0 - 7f19c06f5fc0] {6}{python}: python exception occurred within task:
Traceback (most recent call last):
  File "/home/users/zhihao/legion/apps/FlexFlow/python/flexflow/core/flexflow_top.py", line 195, in flexflow_top_level_task
    run_path(args[start], run_name='__main__')
  File "/home/users/zhihao/legion/apps/FlexFlow/python/flexflow/core/flexflow_top.py", line 145, in run_path
    exec(code, module.__dict__, module.__dict__)
  File "example/alexnet.py", line 174, in <module>
    top_level_task()
  File "example/alexnet.py", line 157, in top_level_task
    cbias = cbias_tensor.get_flat_array(ffconfig, DataType.DT_FLOAT)
  File "/home/users/zhihao/legion/apps/FlexFlow/python/flexflow/core/flexflow_cbinding.py", line 381, in get_flat_array
    array = np.asarray(initializer)
  File "/share/software/user/open/py-numpy/1.14.3_py27/lib/python2.7/site-packages/numpy/core/numeric.py", line 492, in asarray
    return array(a, dtype, copy=False, order=order)
TypeError: __array_interface__ typestr must be a string
```

**Comment by eddy16112** [comment]
Looks like you are using python2.7, the __array_interface__ I used is limited to python3.x

**Comment by jiazhihao** [comment]
It seems when we didn't provide a path to PYTHON_LIB: https://github.com/flexflow/FlexFlow/blob/master/python/Makefile#L37, Legion will first try to find a path for python2 and then python3.

**Comment by eddy16112** [comment]
Yes, I had the same issue before on my machine. That's why I need to manually specify the PYTHON_LIB in the makefile.

**Comment by jiazhihao** [comment]
@eddy16112 I pushed some code that attempts to automatically detect PYTHON_LIB path. https://github.com/flexflow/FlexFlow/blob/master/python/Makefile#L36-L63. It works on Sherlock and Summit. Can you give it a try and see if it works on your machine?

**Comment by eddy16112** [comment]
@jiazhihao I pushed a minor fix of the makefile, as my PYTHON_LIB is under lib64 not lib.
https://github.com/flexflow/FlexFlow/commit/5b69bb4b509a68e6fac897650c1afbe56e4ff53b

**Comment by jiazhihao** [comment]
The changes look great to me.:-)
