### ISSUE TITLE
Accuracy errors

### ISSUE THREAD

**Issue by goliaro** [flexflow/FlexFlow#355]
When running the `$FF_HOME/examples/python/keras/func_mnist_mlp_concat.py` example as part of the python tests (`python/test.sh` script), I get the following error:

```bash
epochs 5, ELAPSED TIME = 62.9667s, interations 937, samples 60000, THROUGHPUT = 4764.42 samples/s

[0 - 7f6504303700]   69.922511 {6}{python}: python exception occurred within task:
Traceback (most recent call last):
  File "/usr/FlexFlow/python/flexflow/core/flexflow_top.py", line 197, in flexflow_top_level_task
    run_path(args[start], run_name='__main__')
  File "/usr/FlexFlow/python/flexflow/core/flexflow_top.py", line 146, in run_path
    exec(code, module.__dict__, module.__dict__)
  File "/usr/FlexFlow/examples/python/keras/func_mnist_mlp_concat.py", line 81, in <module>
    top_level_task()
  File "/usr/FlexFlow/examples/python/keras/func_mnist_mlp_concat.py", line 77, in top_level_task
    model.fit(x_train, y_train, epochs=5, callbacks=[VerifyMetrics(ModelAccuracy.MNIST_MLP), EpochVerifyMetrics(ModelAccuracy.MNIST_MLP)])
  File "/usr/FlexFlow/python/flexflow/keras/models/base_model.py", line 255, in fit
    self._train(epochs, callbacks, eval=False)
  File "/usr/FlexFlow/python/flexflow/keras/models/base_model.py", line 437, in _train
    callback.on_train_end()
  File "/usr/FlexFlow/python/flexflow/keras/callbacks.py", line 73, in on_train_end
    assert 0, "Accuracy is wrong"
AssertionError: Accuracy is wrong
flexflow_python: /usr/FlexFlow/deps/legion/runtime/realm/python/python_module.cc:992: virtual void Realm::LocalPythonProcessor::execute_task(Realm::Processor::TaskFuncID, const Realm::ByteArrayRef&): Assertion `0' failed.
./test.sh: line 43: 115747 Aborted                 (core dumped) ./flexflow_python $FF_HOME/examples/python/keras/func_mnist_mlp_concat.py -ll:py 1 -ll:gpu $GPUS -ll:fsize $LEGION_FSIZE_SMALL -ll:zsize $LEGION_ZSIZE
```

Full output:
<details>
<summary>Toggle here </summary>
<br>

```bash
++ ./flexflow_python /usr/FlexFlow/examples/python/keras/func_mnist_mlp_concat.py -ll:py 1 -ll:gpu 1 -ll:fsize 4096 -ll:zsize 12192
[0 - 7f652ec6a700]    0.387489 {3}{Mapper}: Enabled Control Replication Optimizations.
[0 - 7f652ec6a700]    0.387587 {3}{Mapper}: Enabled Control Replication Optimizations.
[0 - 7f652ec6a700]    0.387602 {3}{Mapper}: Enabled Control Replication Optimizations.
Using cffi flexflow bindings.
Using flexflow python
start top-level task
top-level task
Using flexflow backend.
Functional API, mnist mlp concat
shape:  (60000, 784)
Python API batchSize(64) workersPerNodes(1) numNodes(1)
Python API batchSize(64) workersPerNodes(1) numNodes(1)
Python API batchSize(64) workersPerNodes(1) numNodes(1)
Python API batchSize(64) workersPerNodes(1) numNodes(1)
Python API batchSize(64) workersPerNodes(1) numNodes(1)
workSpaceSize (1024 MB)
legion_axis = 0
num_nodes = 1 num_gpus_per_node = 1
[Measure Concat] name(Concat_1000009_2000009) forward_time(0.0148) backward_time(0.0148)
Optimal cost: 1.3863
digraph taskgraph {
  node0 [label="{ Linear_5000005 | 5000005 | { 1 } | { 0 } }",shape=record];
  node1 -> node0;
  node2 [label="{ Linear_5000006 | 5000006 | { 1 } | { 0 } }",shape=record];
  node0 -> node2;
  node3 [label="{ Concat_5000009 | 5000009 | { 1 } | { 0 } }",shape=record];
  node2 -> node3;
  node4 -> node3;
  node5 -> node3;
  node6 -> node3;
  node4 [label="{ Linear_5000004 | 5000004 | { 1 } | { 0 } }",shape=record];
  node7 -> node4;
  node8 [label="{ Softmax_5000011 | 5000011 | { 1 } | { 0 } }",shape=record];
  node9 -> node8;
  node9 [label="{ Linear_5000010 | 5000010 | { 1 } | { 0 } }",shape=record];
  node3 -> node9;
  node10 [label="{ Linear_5000001 | 5000001 | { 1 } | { 0 } }",shape=record];
  node1 -> node10;
  node5 [label="{ Linear_5000008 | 5000008 | { 1 } | { 0 } }",shape=record];
  node11 -> node5;
  node1 [label=Input_5000000];
  node11 [label="{ Linear_5000007 | 5000007 | { 1 } | { 0 } }",shape=record];
  node1 -> node11;
  node7 [label="{ Linear_5000003 | 5000003 | { 1 } | { 0 } }",shape=record];
  node1 -> node7;
  node6 [label="{ Linear_5000002 | 5000002 | { 1 } | { 0 } }",shape=record];
  node10 -> node6;
}opotimal_views.size = 12
legion_axis = 0
views.size() = 12
Deserialized Views...
node[5000026]: type(Linear_5000026) view(1 1 0)  inEdge(node(5000022) idx(0))
node[5000022]: type(Input_5000022) view(0 0 0) 
node[5000030]: type(Linear_5000030) view(1 1 0)  inEdge(node(5000026) idx(0))
node[5000031]: type(Concat_5000031) view(1 1 0)  inEdge(node(5000027) idx(0)) inEdge(node(5000029) idx(0)) inEdge(node(5000030) idx(0)) inEdge(node(5000028) idx(0))
node[5000033]: type(Softmax_5000033) view(1 1 0)  inEdge(node(5000032) idx(0))
node[5000032]: type(Linear_5000032) view(1 1 0)  inEdge(node(5000031) idx(0))
node[5000023]: type(Linear_5000023) view(1 1 0)  inEdge(node(5000022) idx(0))
node[5000027]: type(Linear_5000027) view(1 1 0)  inEdge(node(5000023) idx(0))
node[5000024]: type(Linear_5000024) view(1 1 0)  inEdge(node(5000022) idx(0))
node[5000028]: type(Linear_5000028) view(1 1 0)  inEdge(node(5000024) idx(0))
node[5000029]: type(Linear_5000029) view(1 1 0)  inEdge(node(5000025) idx(0))
node[5000025]: type(Linear_5000025) view(1 1 0)  inEdge(node(5000022) idx(0))
legion_axis = 0
digraph taskgraph {
  node0 [label="{ Linear_5000027 | { 512/1 | 64/1 | 1/1 } }",shape=record];
  node1 -> node0;
  node2 [label="{ Linear_5000026 | { 512/1 | 64/1 | 1/1 } }",shape=record];
  node3 -> node2;
  node4 [label="{ Linear_5000025 | { 512/1 | 64/1 | 1/1 } }",shape=record];
  node3 -> node4;
  node5 [label="{ Linear_5000024 | { 512/1 | 64/1 | 1/1 } }",shape=record];
  node3 -> node5;
  node3 [label="{ Input_5000022 | { shape([ 784/1 64/1 1/1 ]) } }",shape=record];
  node1 [label="{ Linear_5000023 | { 512/1 | 64/1 | 1/1 } }",shape=record];
  node3 -> node1;
  node6 [label="{ Linear_5000032 | { 10/1 | 64/1 | 1/1 } }",shape=record];
  node7 -> node6;
  node8 [label="{ Softmax_5000033 | { 10/1 | 64/1 | 1/1 } }",shape=record];
  node6 -> node8;
  node7 [label="{ Concat_5000031 | { 2048/1 | 64/1 | 1/1 } }",shape=record];
  node9 -> node7;
  node10 -> node7;
  node11 -> node7;
  node0 -> node7;
  node9 [label="{ Linear_5000030 | { 512/1 | 64/1 | 1/1 } }",shape=record];
  node2 -> node9;
  node11 [label="{ Linear_5000029 | { 512/1 | 64/1 | 1/1 } }",shape=record];
  node4 -> node11;
  node10 [label="{ Linear_5000028 | { 512/1 | 64/1 | 1/1 } }",shape=record];
  node5 -> node10;
}
ndim(1) dims[1 0 0 0]
seed = 1804289383 scale = 0.0680
seed = 846930886 scale = 0.0680
seed = 1681692777 scale = 0.0680
seed = 1714636915 scale = 0.0680
seed = 1957747793 scale = 0.0765
seed = 424238335 scale = 0.0765
seed = 719885386 scale = 0.0765
seed = 1649760492 scale = 0.0765
seed = 596516649 scale = 0.0540
operator[0]: type(0)
outputs[0] region(5,6,1)
operator[1]: type(1)
outputs[0] region(7,7,3)
operator[2]: type(1)
outputs[0] region(9,8,5)
operator[3]: type(5)
inputs[0] region(5,6,1)
outputs[0] region(11,9,7)
operator[4]: type(1)
outputs[0] region(13,10,9)
operator[5]: type(1)
outputs[0] region(15,11,11)
operator[6]: type(5)
inputs[0] region(5,6,1)
outputs[0] region(17,12,13)
operator[7]: type(1)
outputs[0] region(19,13,15)
operator[8]: type(1)
outputs[0] region(21,14,17)
operator[9]: type(5)
inputs[0] region(5,6,1)
outputs[0] region(23,15,19)
operator[10]: type(1)
outputs[0] region(25,16,21)
operator[11]: type(1)
outputs[0] region(27,17,23)
operator[12]: type(5)
inputs[0] region(5,6,1)
outputs[0] region(29,18,25)
operator[13]: type(1)
outputs[0] region(31,19,27)
operator[14]: type(1)
outputs[0] region(33,20,29)
operator[15]: type(5)
inputs[0] region(11,9,7)
outputs[0] region(35,21,31)
operator[16]: type(1)
outputs[0] region(37,22,33)
operator[17]: type(1)
outputs[0] region(39,23,35)
operator[18]: type(5)
inputs[0] region(17,12,13)
outputs[0] region(41,24,37)
operator[19]: type(1)
outputs[0] region(43,25,39)
operator[20]: type(1)
outputs[0] region(45,26,41)
operator[21]: type(5)
inputs[0] region(23,15,19)
outputs[0] region(47,27,43)
operator[22]: type(1)
outputs[0] region(49,28,45)
operator[23]: type(1)
outputs[0] region(51,29,47)
operator[24]: type(5)
inputs[0] region(29,18,25)
outputs[0] region(53,30,49)
operator[25]: type(21)
inputs[0] region(41,24,37)
inputs[1] region(53,30,49)
inputs[2] region(47,27,43)
inputs[3] region(35,21,31)
outputs[0] region(55,31,51)
operator[26]: type(1)
outputs[0] region(57,32,53)
operator[27]: type(1)
outputs[0] region(59,33,55)
operator[28]: type(5)
inputs[0] region(55,31,51)
outputs[0] region(61,34,57)
operator[29]: type(19)
inputs[0] region(61,34,57)
outputs[0] region(63,35,59)
Compiled ffmodel!
Layer (type)            Output Shape            Input Shape     Connected to
input (InputLayer)       (64, 784)              None
dense1 (Dense)           (64, 512)              (64, 784)       input
dense12 (Dense)          (64, 512)              (64, 512)       dense1
dense2 (Dense)           (64, 512)              (64, 784)       input
dense22 (Dense)          (64, 512)              (64, 512)       dense2
dense3 (Dense)           (64, 512)              (64, 784)       input
dense33 (Dense)          (64, 512)              (64, 512)       dense3
dense4 (Dense)           (64, 512)              (64, 784)       input
dense44 (Dense)          (64, 512)              (64, 512)       dense4
concatenate (Concatenate)(64, 2048)     dense12 dense22 dense33 dense44
dense (Dense)            (64, 10)               (64, 2048)      concatenate
softmax (Activation)     (64, 10)               (64, 10)        dense

numpy array: (140052071649296, False), <cdata 'float *' 0x7f6069fb1010>, 0x7f6069fb1010
Index load entire dataset: ptr input_head_ 0x7f6069fb1010, idx 0, input_ 0x7f6069fb1010 140052071649296 47040000, input 0x7f60ad9eb860 140053206448224 47040000
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
numpy array: (140052382137408, False), <cdata 'float *' 0x7f607c7cbc40>, 0x7f607c7cbc40
Index load entire dataset: ptr input_head_ 0x7f607c7cbc40, idx 0, input_ 0x7f607c7cbc40 140052382137408 60000, input 0x7f60b8d5d060 140053394608224 60000
5 0 4 1 9 2 1 3 1 4 3 5 3 6 1 7 2 8 6 9 4 0 9 1 1 2 4 3 2 7 3 8 
init linear (input): in_dim(784) out_dim(512) batch_size(64)
init linear (input): in_dim(784) out_dim(512) batch_size(64)
init linear (input): in_dim(784) out_dim(512) batch_size(64)
init linear (input): in_dim(784) out_dim(512) batch_size(64)
init linear (input): in_dim(512) out_dim(512) batch_size(64)
init linear (input): in_dim(512) out_dim(512) batch_size(64)
init linear (input): in_dim(512) out_dim(512) batch_size(64)
init linear (input): in_dim(512) out_dim(512) batch_size(64)
init linear (input): in_dim(2048) out_dim(10) batch_size(64)
[Metrics] accuracy: 10.937500% (7 / 64) sparse_categorical_crossentropy: 2.302583
[Metrics] accuracy: 8.593750% (11 / 128) sparse_categorical_crossentropy: 2.302568
[Metrics] accuracy: 8.854167% (17 / 192) sparse_categorical_crossentropy: 2.302599
[Metrics] accuracy: 10.156250% (26 / 256) sparse_categorical_crossentropy: 2.302573
[Metrics] accuracy: 10.312500% (33 / 320) sparse_categorical_crossentropy: 2.302582
[Metrics] accuracy: 10.416667% (40 / 384) sparse_categorical_crossentropy: 2.302568
[Metrics] accuracy: 10.714286% (48 / 448) sparse_categorical_crossentropy: 2.302563
[Metrics] accuracy: 11.718750% (60 / 512) sparse_categorical_crossentropy: 2.302550
[Metrics] accuracy: 11.805555% (68 / 576) sparse_categorical_crossentropy: 2.302556

...
...
...

[Metrics] accuracy: 11.240622% (6712 / 59712) sparse_categorical_crossentropy: 2.301215
[Metrics] accuracy: 11.238625% (6718 / 59776) sparse_categorical_crossentropy: 2.301212
[Metrics] accuracy: 11.241645% (6727 / 59840) sparse_categorical_crossentropy: 2.301206
[Metrics] accuracy: 11.239650% (6733 / 59904) sparse_categorical_crossentropy: 2.301208
[Metrics] accuracy: 11.237660% (6739 / 59968) sparse_categorical_crossentropy: 2.301211
epochs 5, ELAPSED TIME = 62.9667s, interations 937, samples 60000, THROUGHPUT = 4764.42 samples/s

[0 - 7f6504303700]   69.922511 {6}{python}: python exception occurred within task:
Traceback (most recent call last):
  File "/usr/FlexFlow/python/flexflow/core/flexflow_top.py", line 197, in flexflow_top_level_task
    run_path(args[start], run_name='__main__')
  File "/usr/FlexFlow/python/flexflow/core/flexflow_top.py", line 146, in run_path
    exec(code, module.__dict__, module.__dict__)
  File "/usr/FlexFlow/examples/python/keras/func_mnist_mlp_concat.py", line 81, in <module>
    top_level_task()
  File "/usr/FlexFlow/examples/python/keras/func_mnist_mlp_concat.py", line 77, in top_level_task
    model.fit(x_train, y_train, epochs=5, callbacks=[VerifyMetrics(ModelAccuracy.MNIST_MLP), EpochVerifyMetrics(ModelAccuracy.MNIST_MLP)])
  File "/usr/FlexFlow/python/flexflow/keras/models/base_model.py", line 255, in fit
    self._train(epochs, callbacks, eval=False)
  File "/usr/FlexFlow/python/flexflow/keras/models/base_model.py", line 437, in _train
    callback.on_train_end()
  File "/usr/FlexFlow/python/flexflow/keras/callbacks.py", line 73, in on_train_end
    assert 0, "Accuracy is wrong"
AssertionError: Accuracy is wrong
flexflow_python: /usr/FlexFlow/deps/legion/runtime/realm/python/python_module.cc:992: virtual void Realm::LocalPythonProcessor::execute_task(Realm::Processor::TaskFuncID, const Realm::ByteArrayRef&): Assertion `0' failed.
./test.sh: line 43: 115747 Aborted                 (core dumped) ./flexflow_python $FF_HOME/examples/python/keras/func_mnist_mlp_concat.py -ll:py 1 -ll:gpu $GPUS -ll:fsize $LEGION_FSIZE_SMALL -ll:zsize $LEGION_ZSIZE
```
</details>

**Comment by eric-zheng** [comment]
We had a similar issue on the multi_gpu_tests in the past. Zhihao fixed that by fixing a bug of the dataloader. Not sure why this happens though.

**Comment by lockshaw** [comment]
@gabrieleoliaro Are you still planning on taking care of this?

**Comment by lockshaw** [comment]
@gabrieleoliaro Status of this?
