### ISSUE TITLE
Error when running the python onnx example

### ISSUE THREAD

**Issue by litaotju** [flexflow/FlexFlow#638]
Error when running the example

```
b510262e017d:#~/sw_scratch/git/flexflow/FlexFlow/examples/python/onnx:$ python ./alexnet.py  |& tee alex.log
Using flexflow backend.
Using cffi flexflow bindings.
Using flexflow python
alexnet onnx
Traceback (most recent call last):
  File "/home/scratch.tali_sw/git/flexflow/FlexFlow/examples/python/onnx/./alexnet.py", line 71, in <module>
    top_level_task()
  File "/home/scratch.tali_sw/git/flexflow/FlexFlow/examples/python/onnx/./alexnet.py", line 10, in top_level_task
    ffconfig = FFConfig()
  File "/opt/conda/lib/python3.10/site-packages/flexflow/core/flexflow_cffi.py", line 493, in __init__
    self.handle = ffc.flexflow_config_create()
  File "/opt/conda/lib/python3.10/site-packages/cffi/api.py", line 912, in __getattr__
    make_accessor(name)
  File "/opt/conda/lib/python3.10/site-packages/cffi/api.py", line 908, in make_accessor
    accessors[name](name)
  File "/opt/conda/lib/python3.10/site-packages/cffi/api.py", line 838, in accessor_function
    value = backendlib.load_function(BType, name)
AttributeError: function/symbol 'flexflow_config_create' not found in library '<None>': python: undefined symbol: flexflow_config_create. Did you mean: 'flexflow_net_config_create'?

```

**Comment by eddy16112** [comment]
You will need to run it as `flexflow_python ./alexnet.py -ll:gpu 1`, after building the flexflow, you will see the `flexflow_python` binary under python directory.

**Comment by lockshaw** [comment]
Just for extra information: we're working on adding the ability to run using the system python rather than using `flexflow_python`. See #590 for current progress

**Comment by litaotju** [comment]
Thanks @eddy16112  @lockshaw , I tried `flexflow_python` and run into different failures

```root@0916a32195d2:/usr/FlexFlow/examples/python/onnx# flexflow_python ./mnist_mlp.py  -ll:gpu 2
[0 - 7fb5b06e2000]    0.207899 {3}{Mapper}: Enabled Control Replication Optimizations.
[0 - 7fb5b06e2000]    0.207977 {3}{Mapper}: Enabled Control Replication Optimizations.
[0 - 7fb5b06e2000]    0.207994 {3}{Mapper}: Enabled Control Replication Optimizations.
Segmentation fault (core dumped)
```

And I am not building flexflow myself, I am using the container provided in the example.

 ghcr.io/flexflow/flexflow-cuda:latest

**Comment by eddy16112** [comment]
Can you please run `LEGION_BACKTRACE=1 flexflow_python ./alexnet.py -ll:gpu 1` and provide the backtrace? @gabrieleoliaro is the container updated?

**Comment by litaotju** [comment]
Got this.
The container hash is bbf1933e069297cfb5f57dd7911d212c45a076ad8c86b2a5fc3b362813c0622f
```
root@470b9678c51c:/usr/FlexFlow/examples/python/onnx# LEGION_BACKTRACE=1 flexflow_python ./alexnet.py -ll:gpu 1 |& tee alex.log
[0 - 7f73e1af0000]    0.317663 {3}{Mapper}: Enabled Control Replication Optimizations.
[0 - 7f73e1af0000]    0.317755 {3}{Mapper}: Enabled Control Replication Optimizations.
Signal 11 received by node 0, process 28 (thread 7f73e1b06000) - obtaining backtrace
Signal 11 received by process 28 (thread 7f73e1b06000) at: stack trace: 14 frames
  [0] = /usr/lib/x86_64-linux-gnu/libc.so.6(+0x43090) [0x7f740485f090]
  [1] = /usr/local/lib/libflexflow.so(FlexFlow::FFMapper::select_task_options(Legion::Internal::MappingCallInfo*, Legion::Task const&, Legion::Mapping::Mapper::TaskOptions&)+0x1fe) [0x7f7424600a2e]
  [2] = /usr/local/lib/liblegion.so.1(Legion::Internal::MapperManager::invoke_select_task_options(Legion::Internal::TaskOp*, Legion::Mapping::Mapper::TaskOptions*, bool*, Legion::Internal::MappingCallInfo*)+0x47) [0x7f7405546107]
  [3] = /usr/local/lib/liblegion.so.1(Legion::Internal::TaskOp::select_task_options(bool)+0xbb) [0x7f74054a36fb]
  [4] = /usr/local/lib/liblegion.so.1(Legion::Internal::TaskOp::enqueue_ready_task(bool, Legion::Internal::RtEvent)+0x9a) [0x7f74054a439a]
  [5] = /usr/local/lib/liblegion.so.1(Legion::Internal::InnerContext::process_enqueue_task_queue()+0x14c) [0x7f74053312fc]
  [6] = /usr/local/lib/liblegion.so.1(Legion::Internal::InnerContext::handle_enqueue_task_queue(void const*)+0x11) [0x7f74053313a1]
  [7] = /usr/local/lib/liblegion.so.1(Legion::Internal::Runtime::legion_runtime_task(void const*, unsigned long, void const*, unsigned long, Realm::Processor)+0x430) [0x7f7405659ef0]
  [8] = /usr/local/lib/librealm.so.1(+0x67255a) [0x7f7406ea655a]
  [9] = /usr/local/lib/librealm.so.1(+0x6ba493) [0x7f7406eee493]
  [10] = /usr/local/lib/librealm.so.1(+0x6ba54a) [0x7f7406eee54a]
  [11] = /usr/local/lib/librealm.so.1(+0x6bcf3c) [0x7f7406ef0f3c]
  [12] = /usr/local/lib/librealm.so.1(+0x6c4ca7) [0x7f7406ef8ca7]
  [13] = /usr/lib/x86_64-linux-gnu/libc.so.6(+0x5b4e0) [0x7f74048774e0]
```

**Comment by litaotju** [comment]
Any update on this issue?

**Comment by lockshaw** [comment]
@jiazhihao @eddy16112 @gabrieleoliaro

**Comment by eddy16112** [comment]
I did not run into any issue. Here is how I run it on my machine:
```
python ../examples/python/onnx/alexnet_pt.py 
./flexflow_python ../examples/python/onnx/alexnet.py -ll:py 1 -ll:gpu 1 -ll:fsize 4096 -ll:zsize 12192
```
