### ISSUE TITLE
Alignment error in gather

### ISSUE THREAD

**Issue by soumyac1999** [flexflow/FlexFlow#686]
The outputs of gather appears to differ from that of PyTorch/Keras in the following example. 

```python
r"""
Gather bug repro

To get flexflow outputs:
flexflow_python gather_bug_align.py  -ll:py 1 -ll:gpu 1 -ll:fsize 15000 \
     -ll:zsize 4000 --only-data-parallel -b 16

To check with keras/torch:
python gather_bug_align.py

"""


import numpy as np


def get_modified_idx(idx, hidden_shape):
    return idx.reshape(-1, 1).repeat(hidden_shape, 1).astype(np.int32)


def top_level_task():
    from flexflow import keras
    import flexflow.keras.optimizers

    intermediate_tensors = []

    bs = 16  # Set to the same number as -b argument to the script
    idx = np.random.randint(0, 14, (10, 16))
    mod_idx = get_modified_idx(idx, 8)

    inp_x = keras.layers.Input(shape=(15, 4))
    inp_idx = keras.layers.Input(mod_idx.shape, dtype="int32")  # b, 160, 8

    x = inp_x  # b, 15, 4

    x = keras.layers.Reshape((x.shape[1]*x.shape[2],))(x)  # b, 15*4
    x = keras.layers.Dense(15*8, use_bias=True)(x); intermediate_tensors.append(x)  # b, 15*8
    x = keras.layers.Reshape((inp_x.shape[1], 8))(x)  # b, 15, 8

    x = keras.backend.internal.gather(x, inp_idx, axis=1); intermediate_tensors.append(x) # b, 160, 8
    out = keras.layers.Reshape((10, 16, 8))(x) # b, 10, 16, 8

    model = flexflow.keras.models.Model([inp_x, inp_idx], out)

    opt = flexflow.keras.optimizers.SGD(learning_rate=0.01)
    model.compile(optimizer=opt, loss='mean_squared_error',
                  metrics=['mean_squared_error'])

    bs = model.ffconfig.batch_size
    x = [np.random.randn(16, 15, 4).astype(np.float32),
         mod_idx[None, ...].repeat(bs, 0).astype(np.int32)]
    y = np.random.randn(bs, 10, 16, 8).astype(np.float32)
    parameters = [l.get_weights(model.ffmodel)
                  for l in model.layers if hasattr(l, 'get_weights')]

    model.fit(x=x, y=y, epochs=1)

    tensor_vals = [t.ffhandle.get_tensor(model.ffmodel)
                   for t in intermediate_tensors]

    return bs, parameters, x, y, tensor_vals


def keras_task(bs, parameters, inps, y, tensor_vals):
    import tensorflow as tf
    import tensorflow.keras as keras
    from keras.layers import Dense, Concatenate, Input, Reshape, Multiply, Add

    bs = 16
    intermediate_tensors = []

    input_x = Input(shape=(15, 4), dtype="float32")
    inp_idx = inps[1][0, :, 0].reshape(10, 16)

    x = input_x

    x = Reshape((x.shape[1]*x.shape[2],))(x)
    x = Dense(15*8)(x); intermediate_tensors.append(x)
    x = Reshape((input_x.shape[1], 8))(x)
    x = tf.gather(x, inp_idx, axis=1); intermediate_tensors.append(x)

    model = keras.models.Model(input_x, intermediate_tensors)

    i = 0
    for l in model.layers:
        if not isinstance(l, Dense):
            continue
        try:
            l.set_weights(parameters[i])
        except ValueError:
            l.set_weights((parameters[i][0].T, parameters[i][1]))
        i += 1

    opt = keras.optimizers.SGD(learning_rate=0.01)
    model.compile(optimizer=opt, loss='mean_squared_error',
                  metrics=['mean_squared_error'])

    out = model(inps[0])
    for i in range(len(out)):
        print('Matching', i)
        if i == 1:
            e = out[i].numpy()  # Keras
            k = tensor_vals[i].reshape(*e.shape)  # Flexflow
            gather_in = out[0].numpy().reshape((16, 15, 8))
            import torch
            torch_idx = get_modified_idx(inp_idx, 8)[None, :].repeat(bs, 0)
            m = torch.gather(torch.tensor(gather_in), 1, torch.tensor(torch_idx).to(torch.long)).numpy()
            m = m.reshape(*e.shape)  # Torch

            '''
            An example of the difference        
            e[1][0][0] matches m[0][0][0] (i.e keras and torch implementations match)
            but these aren't equal to k[1][0][0] (flexflow)

            but e[0][0][0] == m[0][0][0] == k[0][0][0]
            '''
        np.testing.assert_allclose(
            tensor_vals[i].ravel(), out[i].numpy().ravel(),
            atol=1e-5, rtol=1.3e-6)


if __name__ == '__main__':
    import pickle
    import sys
    if len(sys.argv) > 1:
        t = top_level_task()
        pickle.dump(t, open('dump.pkl', 'wb'))
    else:
        t = pickle.load(open('dump.pkl', 'rb'))
        keras_task(*t)
```

**Comment by soumyac1999** [comment]
This requires the changes in #685 to work

**Comment by lockshaw** [comment]
@jiazhihao

**Comment by jiazhihao** [comment]
@soumyac1999 which Python and Keras versions you used? I am getting the following Python error in Keras 
```
Traceback (most recent call last):
  File "gather_bug_align.py", line 117, in <module>
    keras_task(*t)
  File "gather_bug_align.py", line 65, in keras_task
    x = Dense(15*8)(x); intermediate_tensors.append(x)
  File "/home/ubuntu/anaconda3/envs/py37/lib/python3.7/site-packages/keras/engine/base_layer.py", line 463, in __call__
    self.build(unpack_singleton(input_shapes))
  File "/home/ubuntu/anaconda3/envs/py37/lib/python3.7/site-packages/keras/layers/core.py", line 895, in build
    constraint=self.kernel_constraint)
  File "/home/ubuntu/anaconda3/envs/py37/lib/python3.7/site-packages/keras/engine/base_layer.py", line 279, in add_weight
    weight = K.variable(initializer(shape, dtype=dtype),
  File "/home/ubuntu/anaconda3/envs/py37/lib/python3.7/site-packages/keras/initializers.py", line 218, in __call__
    scale /= max(1., float(fan_in + fan_out) / 2)
TypeError: float() argument must be a string or a number, not 'Dimension'
```

**Comment by soumyac1999** [comment]
My environment has Python 3.10.9 and Keras 2.11.0

**Comment by jiazhihao** [comment]
Do you know if it is the forward function or the backward function that causes the misalignment?
Are you able to reproduce this misalignment using a batch size of one?

**Comment by soumyac1999** [comment]
It should be the forward since I haven't done a backward pass in the example. I am not entirely sure about this.

I am checking this but I suspect it will only show up for batch size greater than one. (Since in the example above, the first batch values match)

**Comment by soumyac1999** [comment]
For some reason, the program crashes for batch size less than 9 with the error
```
[0 - 7fd08615c000]    4.724908 {6}{gpu}: CUDA error reported on GPU 0: an illegal memory access was encountered (CUDA_ERROR_ILLEGAL_ADDRESS)
```
It may or may not be some issue with my code. I'll need some time to check it.

**Comment by jiazhihao** [comment]
The issue is that you hardcoded the batch size here ```
    x = [np.random.randn(16, 15, 4).astype(np.float32),
         mod_idx[None, ...].repeat(bs, 0).astype(np.int32)]
```

The batch size for the first np array should be bs instead of 16

**Comment by jiazhihao** [comment]
@soumyac1999 Try #691
