### ISSUE TITLE
NCCL Error when running FlexFlow with the latest NCCL version

### ISSUE THREAD

**Issue by jiazhihao** [flexflow/FlexFlow#830]
I have tried to run FlexFlow inference with the latest NCCL version (v2.18) and observed the following NCCL error
```
nid002080:86174:87702 [2] NCCL INFO misc/nvmlwrap.cc:181 -> 2
nid002080:86174:87701 [1] NCCL INFO misc/nvmlwrap.cc:181 -> 2
nid002080:86174:87703 [3] NCCL INFO misc/nvmlwrap.cc:181 -> 2
nid002080:86174:87700 [0] NCCL INFO misc/nvmlwrap.cc:181 -> 2

nid002080:86174:87702 [2] graph/xml.cc:634 NCCL WARN No NVML device handle. Skipping nvlink detection.
nid002080:86174:87702 [2] NCCL INFO misc/nvmlwrap.cc:181 -> 2

nid002080:86174:87701 [1] graph/xml.cc:634 NCCL WARN No NVML device handle. Skipping nvlink detection.
nid002080:86174:87701 [1] NCCL INFO misc/nvmlwrap.cc:181 -> 2

nid002080:86174:87700 [0] graph/xml.cc:634 NCCL WARN No NVML device handle. Skipping nvlink detection.
nid002080:86174:87700 [0] NCCL INFO misc/nvmlwrap.cc:181 -> 2

nid002080:86174:87703 [3] graph/xml.cc:634 NCCL WARN No NVML device handle. Skipping nvlink detection.
nid002080:86174:87703 [3] NCCL INFO misc/nvmlwrap.cc:181 -> 2

nid002080:86174:87702 [2] graph/xml.cc:634 NCCL WARN No NVML device handle. Skipping nvlink detection.
nid002080:86174:87702 [2] NCCL INFO misc/nvmlwrap.cc:181 -> 2

nid002080:86174:87701 [1] graph/xml.cc:634 NCCL WARN No NVML device handle. Skipping nvlink detection.
nid002080:86174:87701 [1] NCCL INFO misc/nvmlwrap.cc:181 -> 2

nid002080:86174:87700 [0] graph/xml.cc:634 NCCL WARN No NVML device handle. Skipping nvlink detection.
nid002080:86174:87700 [0] NCCL INFO misc/nvmlwrap.cc:181 -> 2

nid002080:86174:87703 [3] graph/xml.cc:634 NCCL WARN No NVML device handle. Skipping nvlink detection.
nid002080:86174:87703 [3] NCCL INFO misc/nvmlwrap.cc:181 -> 2

nid002080:86174:87702 [2] graph/xml.cc:634 NCCL WARN No NVML device handle. Skipping nvlink detection.
nid002080:86174:87702 [2] NCCL INFO misc/nvmlwrap.cc:181 -> 2

nid002080:86174:87702 [2] graph/xml.cc:634 NCCL WARN No NVML device handle. Skipping nvlink detection.
nid002080:86174:87702 [2] NCCL INFO graph/paths.cc:308 -> 2
nid002080:86174:87702 [2] NCCL INFO graph/paths.cc:550 -> 2
nid002080:86174:87702 [2] NCCL INFO init.cc:795 -> 2
nid002080:86174:87702 [2] NCCL INFO init.cc:1309 -> 2
nid002080:86174:87702 [2] NCCL INFO init.cc:1549 -> 2

nid002080:86174:87701 [1] graph/xml.cc:634 NCCL WARN No NVML device handle. Skipping nvlink detection.
nid002080:86174:87702 [2] NCCL INFO init.cc:1587 -> 2
Failed, NCCL error /global/homes/z/zjia/FlexFlow/src/runtime/model.cc:596 'unhandled system error (run with NCCL_DEBUG=INFO for details)'
nid002080:86174:87701 [1] NCCL INFO misc/nvmlwrap.cc:181 -> 2

nid002080:86174:87700 [0] graph/xml.cc:634 NCCL WARN No NVML device handle. Skipping nvlink detection.
nid002080:86174:87700 [0] NCCL INFO misc/nvmlwrap.cc:181 -> 2

nid002080:86174:87703 [3] graph/xml.cc:634 NCCL WARN No NVML device handle. Skipping nvlink detection.
nid002080:86174:87703 [3] NCCL INFO misc/nvmlwrap.cc:181 -> 2

nid002080:86174:87701 [1] graph/xml.cc:634 NCCL WARN No NVML device handle. Skipping nvlink detection.
nid002080:86174:87701 [1] NCCL INFO graph/paths.cc:308 -> 2
nid002080:86174:87701 [1] NCCL INFO graph/paths.cc:550 -> 2
nid002080:86174:87701 [1] NCCL INFO init.cc:795 -> 2
nid002080:86174:87701 [1] NCCL INFO init.cc:1309 -> 2
nid002080:86174:87701 [1] NCCL INFO init.cc:1549 -> 2
nid002080:86174:87701 [1] NCCL INFO init.cc:1587 -> 2
Failed, NCCL error /global/homes/z/zjia/FlexFlow/src/runtime/model.cc:596 'unhandled system error (run with NCCL_DEBUG=INFO for details)'

nid002080:86174:87700 [0] graph/xml.cc:634 NCCL WARN No NVML device handle. Skipping nvlink detection.

nid002080:86174:87703 [3] graph/xml.cc:634 NCCL WARN No NVML device handle. Skipping nvlink detection.
corrupted double-linked list
nid002080:86174:87703 [3] NCCL INFO graph/paths.cc:308 -> 2
nid002080:86174:87703 [3] NCCL INFO graph/paths.cc:550 -> 2
nid002080:86174:87703 [3] NCCL INFO init.cc:795 -> 2
nid002080:86174:87703 [3] NCCL INFO init.cc:1309 -> 2
nid002080:86174:87703 [3] NCCL INFO init.cc:1549 -> 2
nid002080:86174:87703 [3] NCCL INFO init.cc:1587 -> 2
Failed, NCCL error /global/homes/z/zjia/FlexFlow/src/runtime/model.cc:596 'unhandled system error (run with NCCL_DEBUG=INFO for details)'

```

The backtrack is as follows
```
(gdb) bt
#0  0x00007fffdf9a0aa1 in __run_exit_handlers () from /lib64/libc.so.6
#1  0x00007fffdf9a0c7a in exit () from /lib64/libc.so.6
#2  0x00007ffff69a3555 in FlexFlow::Op::init_nccl_comms_task(Legion::Task const*, std::vector<Legion::PhysicalRegion, std::allocator<Legion::PhysicalRegion> > const&, Legion::Internal::TaskContext*, Legion::Runtime*) () from /global/homes/z/zjia/FlexFlow/debug_build/libflexflow.so
#3  0x00007ffff69fddc0 in void Legion::LegionTaskWrapper::legion_task_wrapper<ncclComm*, &FlexFlow::Op::init_nccl_comms_task>(void const*, unsigned long, void const*, unsigned long, Realm::Processor) () from /global/homes/z/zjia/FlexFlow/debug_build/libflexflow.so
#4  0x00007fffe0d46cf9 in Realm::Task::execute_on_processor(Realm::Processor) ()
   from /global/homes/z/zjia/FlexFlow/debug_build/deps/legion/lib/librealm.so.1
#5  0x00007fffe0d46d76 in Realm::KernelThreadTaskScheduler::execute_task(Realm::Task*) ()
   from /global/homes/z/zjia/FlexFlow/debug_build/deps/legion/lib/librealm.so.1
#6  0x00007fffe0d7c45b in Realm::Cuda::GPUTaskScheduler<Realm::KernelThreadTaskScheduler>::execute_task(Realm::Task*) ()
   from /global/homes/z/zjia/FlexFlow/debug_build/deps/legion/lib/librealm.so.1
#7  0x00007fffe0d499ea in Realm::ThreadedTaskScheduler::scheduler_loop() () from /global/homes/z/zjia/FlexFlow/debug_build/deps/legion/lib/librealm.so.1
#8  0x00007fffe0d4bf82 in void Realm::Thread::thread_entry_wrapper<Realm::ThreadedTaskScheduler, &Realm::ThreadedTaskScheduler::scheduler_loop_wlock>(void*)
    () from /global/homes/z/zjia/FlexFlow/debug_build/deps/legion/lib/librealm.so.1
#9  0x00007fffe0d4f26f in Realm::KernelThread::pthread_entry(void*) () from /global/homes/z/zjia/FlexFlow/debug_build/deps/legion/lib/librealm.so.1
#10 0x00007fffdff6b6ea in start_thread () from /lib64/libpthread.so.0
#11 0x00007fffdfa6aa6f in clone () from /lib64/libc.so.6
```

**Comment by lockshaw** [comment]
@jiazhihao Assigning to you for now, feel free to reassign to whoever is actively working on this.
