### ISSUE TITLE
[FF Serve] Can't load a custom LLAMA2 checkpoint locally to work with llm.compile?

### ISSUE THREAD

**Issue by salahzoubi** [flexflow/FlexFlow#993]
I'm trying to load my own fine-tuned version of LLAMA2 7b which I have saved locally. It seems to load the model fine, however, when I try to compile the llm with SSM's to perform decoding, it seems to error out due to the model not being a repository on HF API. 

To reproduce: 
```
import flexflow.serve as ff

ff.init(
    {
        "num_gpus": 1,
        "memory_per_gpu": 10000,
        "zero_copy_memory_per_node": 5000,
    }
)


llm = ff.LLM("models/hermes-7b-hf") #My own custom model that's saved locally

ssms=[]
ssm = ff.SSM("JackFram/llama-68m")
ssms.append(ssm)

generation_config = ff.GenerationConfig(
    do_sample=True, temperature=0.8, topk=20
)

# Compile the SSMs for inference and load the weights into memory
for ssm in ssms:
    ssm.compile(generation_config)

# Compile the LLM for inference and load the weights into memory
llm.compile(generation_config, ssms=ssms)
```

Here's an error trace:

```
Loading hf weights...
Creating directory /home/ubuntu/.cache/flexflow/weights/models/hermes-7b-hf/half-precision (if it doesn't exist)...
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/flexflow/lib/python3.11/site-packages/huggingface_hub/utils/_errors.py", line 261, in hf_raise_for_status
    response.raise_for_status()
  File "/home/ubuntu/anaconda3/envs/flexflow/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/api/models/models/hermes-7b-hf

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/Falcon-LLM-Research/trail.py", line 27, in <module>
    llm.compile(generation_config, ssms=ssms)
  File "/home/ubuntu/anaconda3/envs/flexflow/lib/python3.11/site-packages/flexflow/serve/serve.py", line 329, in compile
    self.__load_hf_weights()
  File "/home/ubuntu/anaconda3/envs/flexflow/lib/python3.11/site-packages/flexflow/serve/serve.py", line 223, in __load_hf_weights
    self.download_hf_weights_if_needed()
  File "/home/ubuntu/anaconda3/envs/flexflow/lib/python3.11/site-packages/flexflow/serve/serve.py", line 153, in download_hf_weights_if_needed
    latest_revision = hf_api.model_info(self.model_name).sha
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/flexflow/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/flexflow/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 1678, in model_info
    hf_raise_for_status(r)
  File "/home/ubuntu/anaconda3/envs/flexflow/lib/python3.11/site-packages/huggingface_hub/utils/_errors.py", line 293, in hf_raise_for_status
    raise RepositoryNotFoundError(message, response) from e
huggingface_hub.utils._errors.RepositoryNotFoundError: 404 Client Error. (Request ID: Root=1-64e0ae76-6fe48ec47d1cc072289f0a75;dd554320-8268-46bb-b1da-3b380ed28313)

Repository Not Found for url: https://huggingface.co/api/models/models/hermes-7b-hf.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.

```

**Comment by brianyu-nexusflowai** [comment]
++ I think the model path passed in needs to be a remote HF path at this time

**Comment by goliaro** [comment]
@salahzoubi Right now FlexFlow Serve directly supports only remote HuggingFace models, but it shouldn't be too difficult to add support for local models. We'll add this to the TODOs!

**Comment by goliaro** [comment]
@salahzoubi Let us know if you are able to load local models now or if you still encounter any problem :)
